name: Deploy to Google Cloud Run

on:
  workflow_call:
    inputs:
      version_tag:
        required: true
        type: string

jobs:
  build-and-deploy-gcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: motu-avb-controller
      SERVICE_NAME: motu-server
      REGION: us-central1
      IMAGE_NAME: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ inputs.config-path }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-action/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |          
          gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME --platform managed --region $REGION --allow-unauthenticated