name: Run Tests, Draft Release and Deploy to PyPi Test
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    uses: ./.github/workflows/run-tests.yml
  update-release-draft:
    needs: run-test
    runs-on: ubuntu-latest
    if: github.repository == 'ChristopherJohnston/motu_server'
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-to-pypi:
    needs: run-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
      run: |
        python -m build ./src
        twine upload -r testpypi ./src/dist/*