name: Run Tests
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest --cache-clear --cov=motu_server src/tests/ > pytest-coverage.txt
      - name: Comment Coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2