name: Run Tests
on:
  workflow_call:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./src
          pip install -r requirements.txt
          pip install -U -r requirements-dev.txt
      - name: Run tests with pytest
        run: |
          pytest --cache-clear --cov=motu_server > pytest-coverage.txt
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: pytest-coverage.txt