name: Run Tests in PR
on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/run-tests.yml

  comment-coverage:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          
      - name: Comment Coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2